# Generated by Django 4.2.1 on 2023-05-20 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('venue_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('hasComputers', models.BooleanField()),
                ('computers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=20)),
                ('createdAt', models.DateField()),
                ('date', models.DateField()),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('purpose', models.CharField(max_length=50)),
                ('computers', models.IntegerField()),
                ('referenceNo', models.CharField(max_length=20, unique=True)),
                ('points', models.IntegerField()),
                ('coins', models.IntegerField()),
                ('status', models.CharField(max_length=5)),
                ('duration', models.FloatField()),
                ('isUsed', models.BooleanField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingApp.user')),
                ('venue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingApp.venue')),
            ],
        ),
    ]
