# Generated by Django 3.2 on 2023-05-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApp', '0002_rename_userid_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='createdAt',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='hasComputers',
            field=models.BooleanField(default=False),
        ),
    ]
