# Generated by Django 3.2 on 2023-05-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApp', '0004_auto_20230521_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='isUsed',
            field=models.BooleanField(default=False),
        ),
    ]
