# Generated by Django 3.2 on 2023-05-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApp', '0005_alter_booking_isused'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='officeName',
            field=models.CharField(choices=[('Conference Room A', 'Conference Room A'), ('Conference Room B', 'Conference Room B'), ('Coworking Space', 'Coworking Space')], default='Coworking Space', max_length=20),
        ),
    ]
