# Generated by Django 3.2 on 2023-05-22 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=20, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('date', models.DateField(null=True)),
                ('startTime', models.TimeField(null=True)),
                ('endTime', models.TimeField(null=True)),
                ('purpose', models.CharField(max_length=50, null=True)),
                ('computers', models.IntegerField(null=True)),
                ('referenceNo', models.CharField(max_length=20, null=True, unique=True)),
                ('points', models.IntegerField(null=True)),
                ('coins', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=10, null=True)),
                ('duration', models.FloatField(null=True)),
                ('isUsed', models.BooleanField(default=False, null=True)),
                ('officeName', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('venue_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, null=True)),
                ('hasComputers', models.BooleanField(default=False, null=True)),
                ('computers', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookingAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('attendee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendee', to='books.user')),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.booking')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.user'),
        ),
        migrations.AddField(
            model_name='booking',
            name='venue_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.venue'),
        ),
    ]
